# Generated by Django 3.2.11 on 2022-04-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_email', models.EmailField(max_length=50)),
                ('d_name', models.TextField(max_length=25)),
                ('d_contactNo', models.IntegerField()),
                ('state', models.TextField(max_length=25)),
                ('city', models.TextField(max_length=25)),
                ('hospital_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=25)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('contactNo', models.IntegerField()),
                ('dob', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
