# Generated by Django 3.2.12 on 2022-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220417_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(default='NULL', max_length=25),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
