# Generated by Django 4.0.4 on 2022-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220520_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_contactNo',
            field=models.CharField(max_length=12),
        ),
    ]
